services:
  - type: web
    name: swiftdrop-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        value: R3SYHU85wX9WHVs4DzXl3pPY0L6cSKy7Hgw-jiqvu_OhoPkEwM966h28HF57Bka4f5vBSK4wpevRLnEWSXRuMw
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_EXPIRY_MINUTES
        value: 1440
      - key: APP_ENV
        value: production
      - key: TWILIO_ACCOUNT_SID
        value: ACe3e8f702343eaad24dd3ee53f3405a4e
      - key: TWILIO_AUTH_TOKEN
        value: eeb1e9abccb8f38a9a9a72012334e9fa
      - key: TWILIO_FROM_NUMBER
        value: "+14843717429"